### ISSUE TITLE
 "Cannot read property 'email' of undefined"

### ISSUE THREAD

**Issue by johnnyxmas** [auth0/webtask-slack-signup#4]
Upon entering a valid email address, the error below is reported. Tested on Safari & Chrome on OSX (all latest versions) as well as IE in Windows 10. 

Test URL:  https://wt-ac69a1b36ac3581e3ff25d56c02fbd1d-0.run.webtask.io/burbsec-signup

{
  "code": 500,
  "error": "Script generated an unhandled synchronous exception.",
  "details": "TypeError: Cannot read property 'email' of undefined",
  "name": "TypeError",
  "message": "Cannot read property 'email' of undefined",
  "stack": "TypeError: Cannot read property 'email' of undefined\n    at module.exports (/data/wt-ac69a1b36ac3581e3ff25d56c02fbd1d-0%2Fburbsec-signup:28:28)\n    at Async.series.createError.code (/data/sandbox/lib/sandbox.js:732:33)\n    at /data/sandbox/node_modules/async/lib/async.js:718:13\n    at Immediate.iterate [as _onImmediate] (/data/sandbox/node_modules/async/lib/async.js:262:13)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)"
}

**Comment by johnnyxmas** [comment]
Closing issue. Did not have Webhooks configured.
